import React, { useState } from "react"

function TempGetTaskData() {
  const [tasksList, setTasksList] = useState([
    {
      id: 1,
      title: "Gå ut med Hunden!",
      description: "Gå ut med hunden så den inte blir fet",
      date: "2023-03-28",
      category: "skola",
    },
    {
      id: 2,
      title: "Tandläkaren!",
      description: "Fixa tänderna",
      date: "2023-03-28",
      category: "skola",
    },
    {
      id: 3,
      title: "Löptur!",
      description: "Spring lite så du inte blir fet",
      date: "2023-03-29",
      category: "skola",
    },
    {
      id: 4,
      title: "Städa garderoben",
      description: "Rensa ut gamla kläder och organisera garderoben",
      date: "2023-03-30",
      category: "övrigt",
    },
    {
      id: 5,
      title: "Läsa bok",
      description: "Ta en paus och läs en bok",
      date: "2023-03-31",
      category: "fritid",
    },
    {
      id: 6,
      title: "Träna core",
      description: "Gör övningar för en starkare mage",
      date: "2023-04-01",
      category: "skola",
    },
    {
      id: 7,
      title: "Tvätta bilen",
      description: "Rengör bilen och tvätta av smutsen",
      date: "2023-04-02",
      category: "övrigt",
    },
    {
      id: 8,
      title: "Måla om rummet",
      description: "Förnya rummet med ny färg",
      date: "2023-04-04",
      category: "övrigt",
    },
    {
      id: 9,
      title: "Löpträning",
      description: "Fortsätt löpträna och förbättra dina tider",
      date: "2023-04-05",
      category: "skola",
    },
    {
      id: 10,
      title: "Laga mat",
      description: "Prova på att laga en ny rätt till middag",
      date: "2023-04-06",
      category: "fritid",
    },
    {
      id: 11,
      title: "Plugga inför tentan",
      description: "Förbered dig inför tentan och gå igenom gamla prov",
      date: "2023-04-07",
      category: "skola",
    },
    {
      id: 12,
      title: "Plantera blommor",
      description: "Fyll trädgården med färgglada blommor",
      date: "2023-04-08",
      category: "fritid",
    },
    {
      id: 13,
      title: "Rensa ur kylskåpet",
      description: "Töm kylskåpet på gamla matvaror och gör en inventering",
      date: "2023-04-09",
      category: "övrigt",
    },
    {
      id: 14,
      title: "Tvätta bilen",
      description: "Tvätta bilen så den blir ren och fin",
      date: "2023-03-29",
      category: "övrigt",
    },
    {
      id: 15,
      title: "Gymträning",
      description: "Träna på gymmet",
      date: "2023-03-30",
      category: "fritid",
    },
    {
      id: 16,
      title: "Läsa bok",
      description: "Läs en bok för att koppla av",
      date: "2023-03-31",
      category: "fritid",
    },
    {
      id: 17,
      title: "Städa rummet",
      description: "Rensa och städa rummet",
      date: "2023-04-01",
      category: "övrigt",
    },
    {
      id: 18,
      title: "Skoluppgift",
      description: "Gör klart skoluppgiften",
      date: "2023-04-02",
      category: "skola",
    },
    {
      id: 19,
      title: "Fira påsk",
      description: "Fira påsk med familjen",
      date: "2023-04-03",
      category: "fritid",
    },
    {
      id: 20,
      title: "Träffa vänner",
      description: "Träffa vänner för att umgås",
      date: "2023-04-04",
      category: "fritid",
    },
    {
      id: 21,
      title: "Planera resa",
      description: "Planera en resa med familjen",
      date: "2023-04-05",
      category: "övrigt",
    },
    {
      id: 22,
      title: "Hemuppgift",
      description: "Gör klart hemuppgiften",
      date: "2023-04-05",
      category: "skola",
    },
    {
      id: 23,
      title: "Laga mat",
      description: "Laga en god middag",
      date: "2023-04-05",
      category: "fritid",
    },
  ])
  return tasksList
}

export default TempGetTaskData
